spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_Q9oZ3qQfd
server:
  port: 8083

custom:
  cognito:
    userpool:
      id: us-east-2_Q9oZ3qQfd
    client:
      id: 7plggcpctgqnmfotuud8feu8ro
    scopes: openid+email
  auth:
    redirect-uri: http://localhost:8083/auth/callback
