spring:
    security:
        oauth2:
            client:
                registration:
                    cognito:
                        client-id: 37fceji0eunuv5q16p324gusim
                        client-secret: h1d08uhqq388r0r29oed0fe7e6hjlfgove5a2nk45jfb115rsr6
                        scope:
                        - email
                        - openid
                        - phone
                        redirect-uri: http://localhost:8083/login/oauth2/code/cognito
                provider:
                    cognito:
                        issuerUri: https://cognito-idp.us-east-2.amazonaws.com/us-east-2_8Y34vKHmH
                        user-name-attribute: username
server:
  port: 8083

custom:
  cognito:
    userpool:
      id: us-east-2_8Y34vKHmH
#     client:
#       id: 7plggcpctgqnmfotuud8feu8ro
#     scopes: openid+email
#   auth:
#     login-uri: https://us-east-2q9oz3qqfd.auth.us-east-2.amazoncognito.com
#     redirect-uri: http://localhost:8083/auth/callback
